name: timetable
description: "📅 Customizable, animated calendar widget including day & week views"
version: 0.2.9
homepage: https://github.com/JonasWanke/timetable
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.23.0-13.0.pre"

dependencies:
  flutter:
    sdk: flutter

  black_hole_flutter: ^0.3.1
  collection: ^1.14.11
  dartx: ^0.7.1
  meta: ^1.3.0
  pedantic: ^1.8.0+1
  rxdart: ^0.26.0
  time_machine:
    path: ../time_machine

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4